name: First workflow

on:
  push:
    branches:
      - main

jobs:
  terraforminit:
    name: init-workflow
    runs on : nitinrunner
    steps:
    - name: first step
    run : echo first step

