name: First workflow

on:
  push:
    branches:
      - main

jobs:
  terraforminit:
    name: initworkflow
    runs-on: nitinrunner   # ✅ should be runs-on, not "runs on"
    steps:
      - name: first step
        run: echo "first step"   # ✅ run must be indented under step
