name: First workflow

on:
  push:
    branches:
      - main

jobs:
  terraforminit:
    name: initworkflow
    runs-on: selfhosted-nitin   # ✅ use label instead of runner name
    steps:
      - name: first step
        run: echo "first step"
